name: CI/CD - Next.js to Azure Static Web Apps

on:
  push:
    branches:
      - dev
      - main

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Mapea ramas a entornos de GitHub
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build && npm run export
        # export genera la carpeta "out" con HTML estático

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ github.ref == 'refs/heads/main' && secrets.deployment_token_prod || secrets.deployment_token_dev }}
          action: "upload"
          app_location: "/"
          output_location: "out"
          skip_app_build: true