name: CI/CD - Next.js to Azure Static Web Apps

on:
  push:
    branches:
      - dev
      - main

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Mapea ramas a entornos de GitHub
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js (static export)
        run: npm run build
        # ⚠️ Asegúrate de tener en next.config.js:
        # module.exports = { output: 'export' }

      - name: Verificar carpeta de salida
        run: ls -la out

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ github.ref == 'refs/heads/main' && secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROD || secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          action: "upload"
          app_location: "/"
          output_location: "out"
          skip_app_build: true

