name: CI/CD - Next.js to Azure Static Web Apps

on:
  push:
    branches:
      - dev
      - main

env:
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: npm ci
        name: Instalar dependencias

      - run: npm run build && npm run export
        name: Compilar Next.js

      - name: Seleccionar token según rama
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "AZURE_TOKEN=${{ secrets.deployment_token_prod }}" >> $GITHUB_ENV
          else
            echo "AZURE_TOKEN=${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}" >> $GITHUB_ENV
          fi

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        env:
          AZURE_TOKEN: ${{ env.AZURE_TOKEN }}
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_TOKEN }}
          action: "upload"
          app_location: "/"
          output_location: "out"
          skip_app_build: true
